name: Run Deploy GAS Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build, Lint, Test and Deploy to Staging
    environment: staging
    defaults:
      run:
        working-directory: ./google-apps-script
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install --frozen-lockfile
      - name: Build for Apps Script
        run: pnpm run build
      - run: cp appsscript.json ../.
      - name: Deploy Apps Script
        uses: daikikatsuragawa/clasp-action@v1.1.0
        with:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          idToken: ${{ secrets.ID_TOKEN }}
          refreshToken: ${{ secrets.REFRESH_TOKEN }}
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          scriptId: ${{ vars.SCRIPT_ID }}
          rootDir: ./google-apps-script
          command: "push"
      - name: Link to deployment
        run:
          echo "Deployed to
          https://docs.google.com/spreadsheets/d/1eunUazlR9qeNVkH29ihF9MCrLtmBNAANByzck2HceX4"
